CMS_Blog_MVC/CMS_Blog/Controllers/BackendController.cs
using CMS_Blog.Models;
using CMS_Blog.SQLite;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Web.Helpers;

namespace CMS_Blog.Controllers
{
    public class BackendController : Controller
    {
        public IActionResult Login() => View();

        [ActionName("Index")]
        public IActionResult Index() => View();

        // POST: /Account/Login
        [HttpPost("Login")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string Name, string Password)
        {
            return View("Index", Blog.Get());
            SqlDatabase database = new SqlDatabase();
            if (database.OpenConnection("SQLite\\CMS_BLOG.db"))
            {
                DataTable returnData =
                        database.readSql(
                                "select * " +
                                "  from User " +
                                " where user_alias = \"" + Name + "\"" +
                                "    or upper(user_email) = \"" + Name.ToUpper() + "\"");


                if (returnData.Rows.Count == 0)
                {
                    ViewData["Error"] = "Login fehlgeschlagen";
                    return View("Login");
                }
                else
                {
                    DataRow row = returnData.Rows[0];
                    string hashedPassword = row["user_password"].ToString();

                    if (Crypto.VerifyHashedPassword(hashedPassword, Password))
                    {
                        return View("Index", Blog.Get());
                    }
                    else
                    {
                        ViewData["Error"] = "Login fehlgeschlagen";
                        return View("Login");
                    }
                }
            }
            else
            {
                ViewData["Error"] = "Login fehlgeschlagen";
                return View("Login");
            }

        }


        [HttpGet("GetBackend")]
        [ActionName("BackendIndex")]
        public IActionResult GetBackend()
        {
            return View("Index");
        }

        [ActionName("Pictures")]
        public IActionResult Pictures()
        {
            return View("Pictures");
        }
    }
}

CMS_Blog_MVC/CMS_Blog/Views/Backend/AddUser.cshtml
<div class="card-body">
    <form>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

CMS_Blog_MVC/CMS_Blog/Views/Backend/Index.cshtml
@model CMS_Blog.Models.Blog

@{
    ViewBag.Title = "Backend Index";
    ViewData["Title"] = "Backend Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Partial("~/Views/Shared/_BackendNavBar.cshtml")

<div class="container-fluid">
    <div class="row">
        @Html.Partial("~/Views/Shared/_Navbar.cshtml", Model)

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <!-- Überschrift -->
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Dashboard</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2"></div>
                </div>
            </div>
            <!----------------->
            <!---<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>
            -->
            <h2>Section title</h2>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Header</th>
                            <th>Header</th>
                            <th>Header</th>
                            <th>Header</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1,001</td>
                            <td>Lorem</td>
                            <td>ipsum</td>
                            <td>dolor</td>
                            <td>sit</td>
                        </tr>
                        <tr>
                            <td>1,002</td>
                            <td>amet</td>
                            <td>consectetur</td>
                            <td>adipiscing</td>
                            <td>elit</td>
                        </tr>
                        <tr>
                            <td>1,003</td>
                            <td>Integer</td>
                            <td>nec</td>
                            <td>odio</td>
                            <td>Praesent</td>
                        </tr>
                        <tr>
                            <td>1,003</td>
                            <td>libero</td>
                            <td>Sed</td>
                            <td>cursus</td>
                            <td>ante</td>
                        </tr>
                        <tr>
                            <td>1,004</td>
                            <td>dapibus</td>
                            <td>diam</td>
                            <td>Sed</td>
                            <td>nisi</td>
                        </tr>
                        <tr>
                            <td>1,005</td>
                            <td>Nulla</td>
                            <td>quis</td>
                            <td>sem</td>
                            <td>at</td>
                        </tr>
                        <tr>
                            <td>1,006</td>
                            <td>nibh</td>
                            <td>elementum</td>
                            <td>imperdiet</td>
                            <td>Duis</td>
                        </tr>
                        <tr>
                            <td>1,007</td>
                            <td>sagittis</td>
                            <td>ipsum</td>
                            <td>Praesent</td>
                            <td>mauris</td>
                        </tr>
                        <tr>
                            <td>1,008</td>
                            <td>Fusce</td>
                            <td>nec</td>
                            <td>tellus</td>
                            <td>sed</td>
                        </tr>
                        <tr>
                            <td>1,009</td>
                            <td>augue</td>
                            <td>semper</td>
                            <td>porta</td>
                            <td>Mauris</td>
                        </tr>
                        <tr>
                            <td>1,010</td>
                            <td>massa</td>
                            <td>Vestibulum</td>
                            <td>lacinia</td>
                            <td>arcu</td>
                        </tr>
                        <tr>
                            <td>1,011</td>
                            <td>eget</td>
                            <td>nulla</td>
                            <td>Class</td>
                            <td>aptent</td>
                        </tr>
                        <tr>
                            <td>1,012</td>
                            <td>taciti</td>
                            <td>sociosqu</td>
                            <td>ad</td>
                            <td>litora</td>
                        </tr>
                        <tr>
                            <td>1,013</td>
                            <td>torquent</td>
                            <td>per</td>
                            <td>conubia</td>
                            <td>nostra</td>
                        </tr>
                        <tr>
                            <td>1,014</td>
                            <td>per</td>
                            <td>inceptos</td>
                            <td>himenaeos</td>
                            <td>Curabitur</td>
                        </tr>
                        <tr>
                            <td>1,015</td>
                            <td>sodales</td>
                            <td>ligula</td>
                            <td>in</td>
                            <td>libero</td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </main>
    </div>
</div>
<script type="text/javascript" src="~/js_jquery/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="~/js_devextreme/dx.all.js"></script>
<script type="text/javascript" src="~/js_bootstrap/bootstrap.min.js"></script>
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>
<!-- Graphs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            datasets: [{
                data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#007bff',
                borderWidth: 4,
                pointBackgroundColor: '#007bff'
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: false
                    }
                }]
            },
            legend: {
                display: false,
            }
        }
    });
</script>

CMS_Blog_MVC/CMS_Blog/Views/Backend/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/signin.css" rel="stylesheet">

@using (Html.BeginForm("Login", "Backend", null, FormMethod.Post, null, new { @class = "form-signin" }))
{
    <img class="mb-4" src="@Url.Content("~/Images/favicon.png")" alt="" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Bitte einloggen</h1>
    <label for="inputEmail" class="sr-only">Email Adresse</label>
    @Html.TextBox("Name", null, new { @class = "form-control", @placeholder = "Email Adresse" })
    <label for="inputPassword" class="sr-only">Passwort</label>
    @Html.Password("Password", null, new { @class = "form-control", @placeholder = "Passwort" })
    <input class="btn btn-lg btn-primary btn-block" value="Einloggen" type="submit" />

    @if (ViewData["Error"] != null)
    {
        <label class="text-danger">Login fehlgeschlagen</label>
    }

    <p class="mt-5 mb-3 text-muted">&copy; 2018</p>
}
<script type="text/javascript" src="~/js_jquery/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="~/js_devextreme/dx.all.js"></script>
<script type="text/javascript" src="~/js_bootstrap/bootstrap.min.js"></script>

CMS_Blog_MVC/CMS_Blog/Views/Backend/Pictures.cshtml
@{
    ViewBag.Title = "Pictures";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/dashboard.css" rel="stylesheet">

@Html.Partial("~/Views/Shared/_BackendNavBar.cshtml")


<div class="container-fluid">
    <div class="row">

        @Html.Partial("~/Views/Shared/_Navbar.cshtml")

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <!-- Überschrift -->
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Bilder</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                    </div>
                </div>
            </div>
            <!----------------->
            <!-- Bilder -->
            <div id="ckfinder"></div>
          
        </main>
    </div>
</div>


<script type="text/javascript" src="~/js_jquery/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="~/js_devextreme/dx.all.js"></script>
<script type="text/javascript" src="~/js_bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="~/ckfinder/ckfinder.js"></script>
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()

    CKFinder.widget('ckfinder');
</script>